services:
  mock-frontend:
    build:
      context: .
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      # Environment
      - ENVIRONMENT=${ENVIRONMENT}
      # Frontend Configuration
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      # PhoenixStore Server Configuration
      - PHOENIXSTORE_PROTOCOL=${PHOENIXSTORE_PROTOCOL}
      - PHOENIXSTORE_HOST=${PHOENIXSTORE_HOST}
      - PHOENIXSTORE_PORT=${PHOENIXSTORE_PORT}
      - PHOENIXSTORE_PUBLIC_HOST=${PHOENIXSTORE_PUBLIC_HOST}
      - PHOENIXSTORE_PUBLIC_PORT=${PHOENIXSTORE_PUBLIC_PORT}
      # WebSocket Configuration
      - WEBSOCKET_PROTOCOL=${WEBSOCKET_PROTOCOL}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_PUBLIC_HOST=${WEBSOCKET_PUBLIC_HOST}
      - WEBSOCKET_PUBLIC_PORT=${WEBSOCKET_PUBLIC_PORT}
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      # Storage Configuration (MinIO)
      - STORAGE_PUBLIC_PROTOCOL=${STORAGE_PUBLIC_PROTOCOL}
      - STORAGE_PUBLIC_HOST=${STORAGE_PUBLIC_HOST}
      - STORAGE_PUBLIC_PORT=${STORAGE_PUBLIC_PORT}

    env_file:
      - .env
    depends_on:
      - phoenixstore
    restart: unless-stopped

  phoenixstore:
    build:
      context: ..
      # context: https://github.com/Hotschmoe/sfe-phoenixstore.git
      target: ${ENVIRONMENT}
    ports:
      - "${PHOENIXSTORE_PORT}:${PHOENIXSTORE_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    environment:
      # Environment
      - ENVIRONMENT=${ENVIRONMENT}
      
      # MongoDB Configuration
      - MONGODB_PROTOCOL=${MONGODB_PROTOCOL}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

      # PhoenixStore Server Configuration
      - PHOENIXSTORE_PROTOCOL=${PHOENIXSTORE_PROTOCOL}
      - PHOENIXSTORE_HOST=${PHOENIXSTORE_HOST}
      - PHOENIXSTORE_PORT=${PHOENIXSTORE_PORT}
      - PHOENIXSTORE_PUBLIC_HOST=${PHOENIXSTORE_PUBLIC_HOST}
      - PHOENIXSTORE_PUBLIC_PORT=${PHOENIXSTORE_PUBLIC_PORT}

      # WebSocket Configuration
      - WEBSOCKET_PROTOCOL=${WEBSOCKET_PROTOCOL}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_PUBLIC_HOST=${WEBSOCKET_PUBLIC_HOST}
      - WEBSOCKET_PUBLIC_PORT=${WEBSOCKET_PUBLIC_PORT}
      - WEBSOCKET_HEARTBEAT_INTERVAL=${WEBSOCKET_HEARTBEAT_INTERVAL}
      - WEBSOCKET_MAX_CLIENTS=${WEBSOCKET_MAX_CLIENTS}
      - WEBSOCKET_PING_TIMEOUT=${WEBSOCKET_PING_TIMEOUT}

      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

      # SMTP Configuration
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}

      # Storage Configuration (MinIO)
      - STORAGE_PROTOCOL=${STORAGE_PROTOCOL}
      - STORAGE_HOST=${STORAGE_HOST}
      - STORAGE_PORT=${STORAGE_PORT}
      - STORAGE_PUBLIC_PROTOCOL=${STORAGE_PUBLIC_PROTOCOL}
      - STORAGE_PUBLIC_HOST=${STORAGE_PUBLIC_HOST}
      - STORAGE_PUBLIC_PORT=${STORAGE_PUBLIC_PORT}
      - STORAGE_CONSOLE_PORT=${STORAGE_CONSOLE_PORT}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - STORAGE_USE_SSL=${STORAGE_USE_SSL}
      - STORAGE_REGION=${STORAGE_REGION}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo-express:
    image: mongo-express
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOEXPRESS_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOEXPRESS_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_PROTOCOL}://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_ADMIN_PASSWORD}
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

  minio:
    image: minio/minio:latest
    ports:
      - "${STORAGE_PORT}:9000"
      - "${STORAGE_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
      MINIO_REGION: ${STORAGE_REGION}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  # MinIO create buckets service
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio ${STORAGE_PROTOCOL}://minio:9000 ${STORAGE_ACCESS_KEY} ${STORAGE_SECRET_KEY};
      /usr/bin/mc mb myminio/phoenixstore;
      /usr/bin/mc anonymous set public myminio/phoenixstore;
      exit 0;
      "

volumes:
  mongodb_data:
  minio_data: